pipelines:
  - name: Matrix_Mania_2
    steps:
      - name: Johny_Stepp
        type: Matrix
        stepletMultipliers:
          runtimes:
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - "20"
          environmentVariables:
            - count: 1
            - count: 2
            - count: 3
            - count: 4
            - count: 5
            - count: 6
            - count: 7
            - count: 8
            - count: 9
            - count: 10
            - count: 11
            - count: 12
            - count: 13
            - count: 14
            - count: 15
            - count: 16
            - count: 17
            - count: 18
            - count: 19
            - count: 21
            - count: 22
            - count: 23
            - count: 24
            
        execution:
          onExecute:
            - git clone https://github.com/movie-web/movie-web.git
            - cd movie-web
            - pwd
            - npm i -g pnpm
            - pnpm i
            - pnpm build
            - pnpm lint
