pipelines:
  - name: pipelines_build
    steps:
      - name: packages_build
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - "20"
        execution:
          onExecute:
            - git clone https://github.com/movie-web/movie-web.git
            - cd movie-web
            - pwd
            - pnpm i
            - pnpm build
            - pnpm lint
